library(fs)
library(magick)
library(dplyr)
library(tidyr)
library(stringr)
library(shiny)
library(googlesheets)
library(lubridate)

source("components/palette_randomizer.r")
source("components/tracking.r")
source("components/collection.r")